
#Argentina
Muertes=xlsread('covid19.xlsx','Argentina','C2:C11');
Recuperado=xlsread('covid19.xlsx','Argentina','D2:D11');
Infectados=xlsread('covid19.xlsx','Argentina','B2:B11');
grafico(Muertes,Infectados,Recuperado,'Argentina')
#Brasil
Muertes=xlsread('covid19.xlsx','Brasil','C2:C11');
Recuperado=xlsread('covid19.xlsx','Brasil','D2:D11');
Infectados=xlsread('covid19.xlsx','Brasil','B2:B11');figure;
grafico(Muertes,Infectados,Recuperado,'Brasil')
#Chile
Muertes=xlsread('covid19.xlsx','Chile','C2:C11');
Recuperado=xlsread('covid19.xlsx','Chile','D2:D11');
Infectados=xlsread('covid19.xlsx','Chile','B2:B11');figure;
grafico(Muertes,Infectados,Recuperado,'Chile')
#Suecia
Muertes=xlsread('covid19.xlsx','Suiza','C2:C11');
Recuperado=xlsread('covid19.xlsx','Suiza','D2:D11');
Infectados=xlsread('covid19.xlsx','Suiza','B2:B11');figure;
grafico(Muertes,Infectados,Recuperado,'Suecia')